### ISSUE TITLE
[INFO] Remove "NX Support" from description 

### ISSUE THREAD

**Issue by WokoSchande** [linuxserver/docker-remmina#14]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Description says: "Currently RDP, VNC, SPICE, NX, XDMCP, SSH and EXEC are supported"

Version history says: "16.12.22: - Rebase to Jammy. Drop nx, xdmcp plugins due to lack of packages. Add Kiosk, Secret, x2go plugins."

And as expected: I dont see any NX protocol in Remmina

### Expected Behavior

The description should be updated

### Steps To Reproduce

No need

### Environment

```markdown
No need
```

### CPU architecture

x86-64

### Docker creation

```bash
No need
```

### Container logs

```bash
No need
```

**Comment by homerr** [comment]
Thanks for letting us know
