### ISSUE TITLE
User and password change

### ISSUE THREAD

**Issue by doman18** [linuxserver/docker-remmina#3]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Obviously securing your connections is the first thing the user would want to do. README says that default credentials are abc/abc and you can use login page to change them. But it says nothing about changing this password or creating and using different user. 
I would like to secure my gateway but i dont even know how to do it. 

------------------------------

## Desired Behavior
Ability to change password or use other user. Or at least some recommendations in readme?

## Current Behavior
Anyone who would come to http://myip:3000 can use my connections.

## Alternatives Considered
Web server authorisation (nginx)

**Comment by aptalca** [comment]
I realize we didn't make that clear. The password is the regular PAM authentication. The user is hardcoded to `abc` but the password can be changed via the passwd command inside the container. On the host, you can use the following change to change it.
`docker exec -it remmina passwd abc`
After a container restart, it should prompt for user/pass

**Comment by doman18** [comment]
Unfortunately your solution didnt work. I changed the password, restarted the container (down/up) and i still can autolog. I tried to login=true, but my password does not work, stil its abc/abc. Like the password info is not saved in volume but on container itself

I also made different user. But when i tried to login with it im getting this

```
connection log
connecting to sesman ip 127.0.01 port 3350
sesman connect ok
sending login info to session manager, please wait
login failed for display 0
```

**Comment by doman18** [comment]
So i made Dockerfile ...
```
FROM ghcr.io/linuxserver/remmina:latest

COPY ./password /password
RUN /password/change-pass.sh
```

**Comment by doman18** [comment]
I tried to use `chpasswd` like this
```
FROM ghcr.io/linuxserver/remmina:latest

COPY ./password /password
# RUN /password/change-pass.sh
RUN chpasswd < /password/creds
```
but im getting Unknown user: abc error
```
```

**Comment by doman18** [comment]
Ok i made mistake ealier because i tried to change username. But i basically removed all my changes, made `docker image prune` to be sure that old image wont interfere and left only those. And this work.

```
version: "2.1"
services:
  remmina:
    build:
      context: .
    image: my-remmina
    container_name: remmina
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
    volumes:
      - ./volume:/config
    ports:
      - 3000:3000
    restart: unless-stopped
```
Dockefile
```
FROM ghcr.io/linuxserver/remmina:latest

#RUN useradd --no-log-init -r -g abc abc

COPY ./credentials /credentials
RUN chpasswd < /credentials
```
credentials
```
abc:mycustompassword
```

Also i tried to manually add new user to test if it works ...
```
docker exec -it remmina adduser myuser
```
... and it yes it is (as long as you wont restart container offcourse). The only thing is that remmina is not added to autostart for this user in openbox. The screen is blank openbox desktop. So you have to manually do RightMouseButton -> Terminal and and issue `remmina`. However lack of time prevented me to moving this creation to Dockerfile, adding autostart and mount users remmina's configs to some persistent volume.

**Comment by aptalca** [comment]
Don't overcomplicate things.

Start fresh. Map the config folder as listed in the readme. Use the command I provided earlier to change the password. That's it. It works. I just tested it. Survives reboots and recreation as the password is stored in the persistent config folder.

**Comment by aptalca** [comment]
For now, you can just create a custom init file that does the `passwd abc foo`

**Comment by thelamer** [comment]
Our desktop base is not security hardened. The password option is more of a keep your kids out of the container type thing. 
If you are pubbing this out to the internet it should be behind a reverse proxy like SWAG with auth. 
The shadow is stored in ephemeral storage, I don't have plans to change this.
You can disable autologin with the env var `AUTO_LOGIN=false` , see here for more options: 
https://github.com/linuxserver/gclient#options
